services:
  db:
    image: postgres:17-alpine
    container_name: catfoodstore_postgres
    env_file:
      - ./catfoodstore_db/.env

    volumes:
      - ./catfoodstore_db/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5433:5432"
    restart: unless-stopped

  backend:
    build:
      context: ./catfoodstore_backend
      dockerfile: Dockerfile
    container_name: catfoodfoodstore_backend
    env_file:
      - ./catfoodstore_backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./catfoodstore-app
      dockerfile: Dockerfile
    container_name: catfoodstore_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: catfoodstore_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: catfoodstore_pgadmin
    env_file:
      - ./catfoodstore_db/.env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
